[project]
name = "chip8"
version = "0.1.0"
description = "CHIP-8 interpreter in Python with a CHIP-48 mode"
readme = "README.md"
authors = [
    { name = "evgstanji"}
]
requires-python = ">=3.14"
dependencies = [
    "pygame-ce>=2.5.8",
]

[project.scripts]
chip8 = "chip8.chip8:main"
chip8-window = "chip8.window:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
]

[tool.mypy]
strict = true
